name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  release:
    types:
      - published

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: SBT Build
        env:
          CI_VERSION: ${{ github.ref }}
        run: sbt "; test; assembly"

      - uses: actions/upload-artifact@v4
        with:
          path: 'server/target/scala-*/*.sh.bat'
          retention-days: 5

      - uses: AButler/upload-release-assets@v3.0
        if: github.event_name == 'release'
        with:
          files: 'server/target/scala-*/*.sh.bat'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
